#!/bin/bash

echo '----------------------------'
echo 'Virgin Islands:' `TZ="America/St_Thomas" date +"%I:%M%p - %m/%d/%y"`
echo 'Mumbai:' `TZ="Asia/Calcutta" date +"%I:%M%p - %m/%d/%y"`
echo 'Paris:' `TZ="Europe/Paris" date +"%I:%M%p - %m/%d/%y"`
echo 'NYC:' `TZ="America/New_York" date +"%I:%M%p - %m/%d/%y"`
echo 'Minneapolis:' `TZ="America/Chicago" date +"%I:%M%p - %m/%d/%y"`
echo 'Reijkjavik:' `TZ="Europe/Reijkjavik" date +"%I:%M%p - %m/%d/%y"`
echo 'Melbourne:' `TZ="Australia/Melbourne" date +"%I:%M%p - %m/%d/%y"`
echo 'Berlin:' `TZ="Europe/Berlin" date +"%I:%M%p - %m/%d/%y"`
echo 'Seoul:' `TZ="Asia/Seoul" date +"%I:%M%p - %m/%d/%y"`
echo 'Portland:' `TZ="America/Los_Angeles" date +"%I:%M%p - %m/%d/%y"`
echo '----------------------------'
